name: pull-request-tests
on:
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set environment variables
        run: cat development.env >> $GITHUB_ENV

      - name: Build docker image
        run: docker-compose build
        
      - name: Run tests in docker container
        run: docker-compose run tests-config test
